- hosts: spring
  user: macmini
  become: yes
  become_method: sudo
  tasks:
    - include: ./tasks/setup_directory.yml
      vars:
        group: group1
    - include: ./tasks/setup_directory.yml
      vars:
        group: group2
